# Generated by Django 5.2.7 on 2026-03-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_is_approved'),
    ]

    operations = [

        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
