# Generated by Django 5.2.7 on 2026-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this post on the website'),
        ),
    ]
