# Generated by Django 5.2.5 on 2025-10-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_resource_description'),
    ]

    operations = [

        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
