# Generated by Django 5.2.5 on 2025-10-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_comment_post_remove_commentlike_comment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourceView",
        ),
        migrations.DeleteModel(
            name="AboutMeConfiguration",
        ),
        migrations.DeleteModel(
            name="ResourcesConfiguration",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="resource",
                    name="categories",
                ),
                migrations.RemoveField(
                    model_name="resource",
                    name="technologies",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS portfolio_resource_categories;",
                    reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS portfolio_resource_technologies;",
                    reverse_sql=migrations.RunSQL.noop
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="ResourceCategory",
        ),
    ]
