# Generated by Django 5.2.7 on 2026-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_remove_project_youtube_url_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='achievement',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this achievement on the website'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this experience on the website'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this project on the website'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this skill on the website'),
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
        migrations.DeleteModel(
            name='ProjectCommentLike',
        ),
    ]
