# Generated by Django 5.2.7 on 2026-03-07 23:30

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_add_visibility_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='category',
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.FileField(blank=True, help_text='Skill icon (supports all image formats including SVG, WebP)', null=True, upload_to='tech_icons/', validators=[portfolio.models.validate_image_file]),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
