# Generated by Django 5.2.7 on 2026-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_remove_skill_simplify_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon_url',
            field=models.TextField(blank=True, help_text='OR paste an external icon URL or Markdown (e.g., [![My Skills](https://skillicons.dev/...)](...)). This overrides the uploaded file.', null=True),
        ),
    ]
