# Generated by Django 5.2.7 on 2026-03-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquery',
            name='attachment',
        ),
    ]
